version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/app/chroma_data
    environment:
      - EMBEDDING_API_URL=${EMBEDDING_API_URL}
      - LLM_API_URL=${LLM_API_URL}
      - EMBEDDING_DIM=${EMBEDDING_DIM}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
